<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKghPjfN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKghPjfN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKghPjfN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKghPjfN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKghPjfN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KghPjfN',
    'container.build_id' => '2e436670',
    'container.build_time' => 1551356300,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKghPjfN');
